### PR TITLE
limit verbosity of tar

### PR DESCRIPTION
**Pull request by nicolasThal**
I would like to limit the verbosity output of the tar.

This would increase the readability of the provisionning.

Regards,
Nicolas

### CODE REVIEW

**Comment by brad** [comment]
Good idea

**Comment by JasonGiedymin** [comment]
I'd like to further improve it with a verbose var to allow switching.

-Jason

**Comment by nicolasThal** [comment]
Thanks for the merge :)

I think that the var to switch can be a good idea!!

**Comment by JasonGiedymin** [comment]
Start on it!

-Jason

**Comment by nicolasThal** [comment]
Tomorrow for sure ;) !!

**Comment by brad** [comment]
Sorry @JasonGiedymin Guess I got a little over zealous on this one. I don't personally see the use for verbosity here.

**Comment by JasonGiedymin** [comment]
You know, that's right. No real use, I guess debugging. However that's better served doing archive checksum validation instead.

**Pull request merged**
